IF NOT EXISTS CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar,
    login varchar,
    name varchar,
    birthday date
);

IF NOT EXISTS CREATE TABLE friends (
    user_id integer,
    friend_id integer,
    confirmed boolean
);
