CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar,
    login varchar,
    name varchar,
    birthday date
);

CREATE TABLE IF NOT EXISTS friends (
    user_id integer,
    friend_id integer,
    confirmed boolean
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    description text,
    release_date date,
    duration integer,
    age_rating integer
);

CREATE TABLE IF NOT EXISTS film_likes (
    film_id integer,
    user_id integer
);

CREATE TABLE IF NOT EXISTS film_genres (
    film_id integer,
    genre_id integer
);

CREATE TABLE IF NOT EXISTS genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    description text
);

CREATE TABLE IF NOT EXISTS age_ratings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    description text
);
