IF NOT EXISTS CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar,
    login varchar,
    name varchar,
    birthday date
);

IF NOT EXISTS CREATE TABLE friends (
    user_id integer,
    friend_id integer,
    confirmed boolean
);

IF NOT EXISTS CREATE TABLE films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    description text,
    release_date date,
    duration integer,
    age_rating integer
);

IF NOT EXISTS CREATE TABLE film_likes (
    film_id integer,
    user_id integer
);


